version: '3.8'

services:
  # Servicio del Backend
  backend:
    build: ./backend
    container_name: barberia-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/barberia_db?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - db
    networks:
      - app-network

  # Servicio del Frontend
  frontend:
    build: ./frontend
    container_name: barberia-frontend
    ports:
      - "5173:80" # Mapeamos el 5173 (típico de Vite) o el 80 de tu máquina al 80 del contenedor
    depends_on:
      - backend
    networks:
      - app-network

  # Base de datos (Opcional, si tu App la requiere)
  db:
    image: mysql:8.0
    container_name: barberia-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: barberia_db
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/mysql

networks:
  app-network:
    driver: bridge

volumes:
  db_data: